# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xb4\x01\n\rTelemetryData\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x15\n\rcpu_usage_pct\x18\x02 \x01(\x02\x12\x15\n\rram_usage_pct\x18\x03 \x01(\x02\x12\x19\n\x11kb_events_per_min\x18\x04 \x01(\x05\x12\x1c\n\x14mouse_events_per_min\x18\x05 \x01(\x05\x12\x14\n\x0cnet_io_bytes\x18\x06 \x01(\x03\x12\x15\n\rprocess_count\x18\x07 \x01(\x05\"5\n\x11TelemetryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2a\n\x10TelemetryService\x12M\n\x0fStreamTelemetry\x12\x18.telemetry.TelemetryData\x1a\x1c.telemetry.TelemetryResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYDATA']._serialized_start=31
  _globals['_TELEMETRYDATA']._serialized_end=211
  _globals['_TELEMETRYRESPONSE']._serialized_start=213
  _globals['_TELEMETRYRESPONSE']._serialized_end=266
  _globals['_TELEMETRYSERVICE']._serialized_start=268
  _globals['_TELEMETRYSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
